# Generated by Django 6.0.3 on 2026-03-27 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=100)),
                ('zuzendaria', models.CharField(max_length=60)),
                ('urtea', models.IntegerField()),
                ('generoa', models.CharField(max_length=2)),
                ('sinopsia', models.CharField(max_length=500)),
                ('bozkak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bozkatzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gogoko_filmak', models.ManyToManyField(to='filmak.filma')),
            ],
        ),
    ]
